This notebook assume one has activated the conda environment: `Summer2026-py311` (in the workstation).

# Opening and accessing the file

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

import sys
sys.path.append((Path.cwd().parent / "utils").as_posix())
from files_io import h5load

main_dir = Path("/users/shared.user/Summer2026/cogwheel_O4_gaussian_injections/PE/IntrinsicLVCPrior/")

unlensed = main_dir / "unlensed_samples/processed_samples"
images_2 = main_dir / "2_images_samples/processed_samples"
images_3 = main_dir / "3_images_samples/processed_samples"
images_4 = main_dir / "4_images_samples/processed_samples"

all_unlensed = list(unlensed.glob("*.h5"))
all_images_2 = list(images_2.glob("*.h5"))
all_images_3 = list(images_3.glob("*.h5"))
all_images_4 = list(images_4.glob("*.h5"))

In [ ]:
# Show the available files in each directory
print(f"Unlensed samples: {len(all_unlensed)}")
print(f"2-images samples: {len(all_images_2)}")
print(f"3-images samples: {len(all_images_3)}")
print(f"4-images samples: {len(all_images_4)}")

Unlensed samples: 1486
2-images samples: 9925
3-images samples: 2974
4-images samples: 3978


In [ ]:
# Try access the first file in the 2-images samples
target_file = all_images_2[0]
print(f"The filename is: {target_file.name}")

df = h5load(target_file)
print(f"The event name is {df.attrs['event_name']}")

The filename is: MD_SDSS_l2_1001_1_bilby_style_samples.h5
The event name is MD_SDSS_l2_1001_1


# Plotting

# Loading with FIGARO

In [ ]:
# Need this if not running within the GitHub directory
# sys.path.append((Path.cwd().parent / "data_processing").as_posix())
from load_cogwheel_data import load_data

In [ ]:
loaded_data, event_names = load_data(
    dir_path=images_2,
    seed=False,
    par=['m1', 'm2'],
    n_samples=-1,
)

print(event_names)

Loading events: 100%|██████████| 9925/9925 [05:58<00:00, 27.65it/s]


([array([[ 60.4621038 ,  32.83380754],
         [129.12708677,  19.14369902],
         [101.29824362,  37.6993518 ],
         ...,
         [ 81.16706244,  37.7710235 ],
         [ 79.1595383 ,  37.8035444 ],
         [ 75.56446322,  37.59906921]]),
  array([[28.15633301, 21.79333465],
         [48.21665435, 10.33359478],
         [26.76717612, 22.90965491],
         ...,
         [32.84051533, 17.36979439],
         [29.41293292, 19.72063757],
         [33.42049672, 18.63150741]]),
  array([[33.28615239, 21.1730892 ],
         [32.06573955, 20.45579327],
         [25.05121068, 20.80036505],
         ...,
         [32.65516713, 22.38968039],
         [31.31404542, 23.0014373 ],
         [32.96445331, 21.81198217]]),
  array([[31.35423769, 30.81555238],
         [40.66850273, 24.56368614],
         [36.80246293, 23.42477136],
         ...,
         [30.25137723, 25.63002469],
         [29.58725255, 24.31070052],
         [28.85410857, 22.3049522 ]]),
  array([[92.13600747, 45.81770343],